server:
    port: 16016
spring:
    application:
        name: barsys
    datasource:
        url: jdbc:postgresql://localhost:5433/postgres
        username: dbuser
        password: dbpass
        driver-class-name: org.postgresql.Driver